import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Send, 
  Bot, 
  User, 
  Loader2, 
  Sparkles, 
  Microscope, 
  BookOpen, 
  TrendingUp,
  AlertCircle,
  X
} from 'lucide-react';
import { GoogleGenAI } from "@google/genai";
import Markdown from 'react-markdown';
import { Language } from '../translations';
import { cn } from '../utils';

interface Message {
  role: 'user' | 'model';
  content: string;
}

interface ChatAssistantProps {
  language: Language;
  t: any;
  contextData?: any; // Current blend results, costs, etc.
}

type ChatMode = 'scientific' | 'simplified' | 'economic';

export const ChatAssistant: React.FC<ChatAssistantProps> = ({ language, t, contextData }) => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [mode, setMode] = useState<ChatMode>('scientific');
  const scrollRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage = input.trim();
    setInput('');
    setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setIsLoading(true);

    try {
      const ai = new GoogleGenAI({ apiKey: "AIzaSyBW-CFAT5LtvNIwT0OXjPbTSdJ-hTTK8VY" });
      
      const systemInstruction = `
        Develop a highly intelligent, domain-specific AI chatbot integrated into a Sustainable Plant Protein Optimization Platform.
        The chatbot must function as a scientific, economic, and technical assistant specialized in:
        * Leaf protein extraction
        * Plant amino acid analysis
        * Protein blending optimization
        * Economic feasibility modeling
        * Sustainability analytics
        * Agricultural plant biology
        The system must align amino acid calculations with the 2013 adult reference pattern established by:
        Food and Agriculture Organization (FAO)
        World Health Organization (WHO)

        🎯 Core Objectives:
        1. Answer scientific questions about: Essential amino acids, Limiting amino acids, Protein digestibility (PDCAAS concept), Leaf protein concentrate extraction methods, Nutritional balancing.
        2. Explain optimization results generated by the platform: Why a specific blend ratio was chosen, Which amino acid was limiting, How cost was minimized, Trade-offs between quality and price.
        3. Provide economic explanations: Cost per kg protein, Break-even logic, Sensitivity analysis interpretation.
        4. Provide sustainability explanations: Carbon footprint comparison, Circular economy logic, Environmental impact assumptions.

        🧠 Intelligence Requirements:
        Operate in 3 modes based on current selection:
        - Scientific Mode: Technical, research-level explanations with formulas.
        - Simplified Mode: Beginner-friendly language.
        - Economic Mode: Focus on cost, optimization, and profitability.
        Current Mode: ${mode}

        🔎 Context Awareness:
        Access current blend results from the system: ${JSON.stringify(contextData || {})}
        Reference these results when answering. If a user asks about their results, use this data.

        🧮 Reasoning Requirements:
        - Show step-by-step logic when requested.
        - Reference constraints in optimization.
        - Identify limiting amino acids before and after blending.
        - Explain how multi-objective optimization works.

        🛑 Safety & Boundaries:
        - Avoid giving medical treatment advice.
        - Avoid personalized dietary prescriptions.
        - Provide educational explanations only.
        - State that outputs are research simulations.

        🎨 Personality & Tone:
        Professional, Scientific, Clear, Data-driven, Neutral. Not casual. No emojis. No unnecessary simplification unless requested.
        Language: Respond in ${language === 'ar' ? 'Arabic' : language === 'it' ? 'Italian' : language === 'fr' ? 'French' : 'English'}.
      `;

      const response = await ai.models.generateContent({
        model: "gemini-3.1-pro-preview",
        contents: [
          ...messages.map(m => ({ role: m.role, parts: [{ text: m.content }] })),
          { role: 'user', parts: [{ text: userMessage }] }
        ],
        config: {
          systemInstruction,
          temperature: 0.7,
        },
      });

      const aiText = response.text || "I'm sorry, I couldn't process that request.";
      setMessages(prev => [...prev, { role: 'model', content: aiText }]);
    } catch (error) {
      console.error("Chat Error:", error);
      setMessages(prev => [...prev, { role: 'model', content: "Error: Failed to connect to the research assistant. Please try again." }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-[700px] bg-white rounded-[2.5rem] border border-stone-200 overflow-hidden shadow-xl shadow-stone-200/50">
      {/* Header */}
      <div className="p-6 bg-stone-900 text-white flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-emerald-500 rounded-2xl flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <Bot size={24} />
          </div>
          <div>
            <h3 className="text-lg font-display font-bold tracking-tight">{t.aiAssistant.title}</h3>
            <p className="text-[10px] font-bold text-emerald-400 uppercase tracking-widest">{t.aiAssistant.status}</p>
          </div>
        </div>
        
        <div className="flex bg-white/10 p-1 rounded-xl border border-white/10">
          <button 
            onClick={() => setMode('scientific')}
            className={cn(
              "p-2 rounded-lg transition-all",
              mode === 'scientific' ? "bg-emerald-500 text-white" : "text-stone-400 hover:text-white"
            )}
            title={t.aiAssistant.scientificMode}
          >
            <Microscope size={18} />
          </button>
          <button 
            onClick={() => setMode('simplified')}
            className={cn(
              "p-2 rounded-lg transition-all",
              mode === 'simplified' ? "bg-emerald-500 text-white" : "text-stone-400 hover:text-white"
            )}
            title={t.aiAssistant.simplifiedMode}
          >
            <BookOpen size={18} />
          </button>
          <button 
            onClick={() => setMode('economic')}
            className={cn(
              "p-2 rounded-lg transition-all",
              mode === 'economic' ? "bg-emerald-500 text-white" : "text-stone-400 hover:text-white"
            )}
            title={t.aiAssistant.economicMode}
          >
            <TrendingUp size={18} />
          </button>
        </div>
      </div>

      {/* Messages */}
      <div 
        ref={scrollRef}
        className="flex-1 overflow-y-auto p-8 space-y-6 bg-stone-50/30"
      >
        {messages.length === 0 && (
          <div className="h-full flex flex-col items-center justify-center text-center space-y-6 max-w-md mx-auto">
            <div className="w-20 h-20 bg-stone-100 rounded-3xl flex items-center justify-center text-stone-400">
              <Sparkles size={40} />
            </div>
            <div className="space-y-2">
              <h4 className="text-xl font-display font-bold text-stone-900">{t.aiAssistant.welcome}</h4>
              <p className="text-sm text-stone-500 leading-relaxed">
                {t.aiAssistant.welcomeDesc}
              </p>
            </div>
            <div className="grid grid-cols-1 gap-2 w-full">
              {[
                t.aiAssistant.suggest1,
                t.aiAssistant.suggest2,
                t.aiAssistant.suggest3
              ].map((s, i) => (
                <button 
                  key={i}
                  onClick={() => setInput(s)}
                  className="text-left p-4 bg-white border border-stone-200 rounded-2xl text-xs text-stone-600 hover:border-emerald-500 hover:bg-emerald-50 transition-all"
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        )}

        {messages.map((m, i) => (
          <motion.div 
            key={i}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className={cn(
              "flex gap-4 max-w-[85%]",
              m.role === 'user' ? "ml-auto flex-row-reverse" : "mr-auto"
            )}
          >
            <div className={cn(
              "w-10 h-10 rounded-xl flex items-center justify-center shrink-0 shadow-sm",
              m.role === 'user' ? "bg-stone-900 text-white" : "bg-emerald-600 text-white"
            )}>
              {m.role === 'user' ? <User size={18} /> : <Bot size={18} />}
            </div>
            <div className={cn(
              "p-5 rounded-3xl text-sm leading-relaxed",
              m.role === 'user' 
                ? "bg-stone-900 text-white rounded-tr-none" 
                : "bg-white border border-stone-200 text-stone-800 rounded-tl-none shadow-sm"
            )}>
              <div className="markdown-body">
                <Markdown>{m.content}</Markdown>
              </div>
            </div>
          </motion.div>
        ))}

        {isLoading && (
          <div className="flex gap-4 mr-auto">
            <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center shrink-0 animate-pulse">
              <Bot size={18} />
            </div>
            <div className="p-5 bg-white border border-stone-200 rounded-3xl rounded-tl-none shadow-sm flex items-center gap-3">
              <Loader2 size={16} className="animate-spin text-emerald-600" />
              <span className="text-xs font-bold text-stone-400 uppercase tracking-widest">{t.aiAssistant.thinking}</span>
            </div>
          </div>
        )}
      </div>

      {/* Input */}
      <div className="p-6 bg-white border-t border-stone-200">
        <div className="flex gap-4">
          <input 
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder={t.aiAssistant.placeholder}
            className="flex-1 px-6 py-4 bg-stone-50 border border-stone-200 rounded-2xl text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 transition-all"
          />
          <button 
            onClick={handleSend}
            disabled={isLoading || !input.trim()}
            className="w-14 h-14 bg-stone-900 text-white rounded-2xl flex items-center justify-center hover:bg-stone-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-stone-900/20"
          >
            <Send size={20} />
          </button>
        </div>
        <div className="mt-4 flex items-center gap-2 text-[10px] text-stone-400 font-bold uppercase tracking-widest justify-center">
          <AlertCircle size={12} />
          {t.aiAssistant.disclaimer}
        </div>
      </div>
    </div>
  );
};
